name: ci
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: initialize bats
        run: |
          cd ${{ github.workspace }} && git submodule init --recursive
      - name: test
        run: |
          cd ${{ github.workspace }} && ./bin/test
      - name: lint
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          scandir: './src'
