name: ish ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: TEMPORARILY install netcat
        run: sudo apt-get install -y netcat
      - name: test
        run: |
          cd ${{ github.workspace }} && ./bin/test
      - name: lint
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          scandir: './src'
