name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: test
        run: |
          cd ${{ github.workspace }} && ./bin/test
