name: validate
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: test
        run: |
          cd ${{ github.workspace }} && ./bin/test
      - name: lint
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          scandir: './src'
